os:
  - linux

dist: xenial

sudo: required

services:
  - docker

language: node_js

before_install:
  - sudo apt-get update
  - sudo apt-get dist-upgrade
  - wget https://github.com/clnperez/cli/releases/download/1.0/docker-linux-amd64
  - chmod 755 docker-linux-amd64

  - ./init-repo.sh ./

  - docker pull multiarch/qemu-user-static:register
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - ./build.sh

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
