os:
  - linux
sudo: required
services:
  - docker
language: node_js
node_js:
  - "8.11.3"
cache:
  yarn: true
  directories:
    - node
    - node_modules
    - $HOME/.yarn-cache
env:
  global:
    - NODE_VERSION=8.11.3
before_install:
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
script:
  #- yarn test
  - yarn build
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # get qemu-arm-static binary
  - mkdir tmp
  - >
    pushd tmp &&
    curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz &&
    tar xzf qemu-arm-static.tar.gz &&
    popd
  # build image
  - docker build -t t08094a/rpi-alarmdisplay-app:build -f ./Dockerfile.arm64 .
  # test image
  - docker run t08094a/rpi-alarmdisplay-app:build uname -a
  # push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [[ $TRAVIS_PULL_REQUEST == "false" ]]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      TAG=$(grep "FROM " Dockerfile.arm | sed 's/.*://')
      docker tag t08094a/rpi-alarmdisplay-app:build t08094a/rpi-alarmdisplay-app:$TAG
      docker tag t08094a/rpi-alarmdisplay-app:build t08094a/rpi-alarmdisplay-app:latest
      docker push t08094a/rpi-alarmdisplay-app:$TAG
      docker push t08094a/rpi-alarmdisplay-app:latest
    fi
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
